Traceback (most recent call last):
  File "/home/ubuntu/video-game-nation/./vgn_fantasy_bot.py", line 6, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
